version: "3.9"
services:
  frontend:
    build: ./SinglePageBlogFrontEnd
    volumes:
      - ./SinglePageBlogFrontEnd/:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - app
  app:
    build: .
    env_file: 
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
  
volumes:
  postgres_data:

