# Generated by Django 3.2.3 on 2021-05-26 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
