# Generated by Django 3.2.3 on 2021-06-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion '), ('Food', 'Food'), ('Travel', 'Travel'), ('Music', 'Music'), ('Lifestyle', 'Lifestyle'), ('Fitness', 'Fitness'), ('DIY', 'DIY'), ('Sports', 'Sports'), ('Political', 'Political'), ('Tech', 'Tech'), ('Gaming', 'Gaming'), ('Pet', 'Pet')], default=None, max_length=50, null=True),
        ),
    ]
